language: go
go:
  - "1.13.x"
  - "1.14.x"
go_import_path: github.com/schoukri/golist
env:
  - GO111MODULE=on
matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet .
  - go test -v -race ./...
