// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2020-04-08 00:13:30.742312 +0000 UTC.

package golist

import (
	"fmt"
	"math/rand"
	"time"
)

// SliceBool is a slice of type bool.
type SliceBool struct {
	data []bool
}

// NewSliceBool returns a pointer to a new SliceBool initialized with the specified elements.
func NewSliceBool(elems ...bool) *SliceBool {
	s := new(SliceBool)
	s.data = make([]bool, len(elems))
	for i := 0; i < len(elems); i++ {
		s.data[i] = elems[i]
	}
	return s
}

// Append adds the elements to the end of SliceBool.
func (s *SliceBool) Append(elems ...bool) *SliceBool {
	if s == nil {
		return nil
	}
	s.data = append(s.data, elems...)
	return s
}

// Prepend adds the elements to the beginning of SliceBool.
func (s *SliceBool) Prepend(elems ...bool) *SliceBool {
	if s == nil {
		return nil
	}
	s.data = append(elems, s.data...)
	return s
}

// At returns the element in SliceBool at the specified index.
func (s *SliceBool) At(index int) bool {
	if s.data == nil || len(s.data) == 0 {
		panic("SliceBool does not contain any elements")
	}

	if index >= len(s.data) || index < 0 {
		panic(fmt.Sprintf("index %d outside the range of SliceBool", index))
	}

	return s.data[index]
}

// Set sets the element of SliceBool at the specified index.
func (s *SliceBool) Set(index int, elem bool) *SliceBool {
	if s == nil {
		return nil
	}
	s.data[index] = elem
	return s
}

// Insert inserts the elements into SliceBool at the specified index.
func (s *SliceBool) Insert(index int, elems ...bool) *SliceBool {
	if s == nil {
		return nil
	}

	// Grow the slice by the number of elements (using the zero value)
	var zero bool
	for i := 0; i < len(elems); i++ {
		s.data = append(s.data, zero)
	}

	// Use copy to move the upper part of the slice out of the way and open a hole.
	copy(s.data[index+len(elems):], s.data[index:])

	// Store the new values
	for i := 0; i < len(elems); i++ {
		s.data[index+i] = elems[i]
	}

	// Return the result.
	return s
}

// Remove removes the element from SliceBool at the specified index.
func (s *SliceBool) Remove(index int) *SliceBool {
	if s == nil {
		return nil
	}
	s.data = append(s.data[:index], s.data[index+1:]...)
	return s
}

// Filter removes elements from SliceBool that do not satisfy the filter function.
func (s *SliceBool) Filter(fn func(elem bool) bool) *SliceBool {
	if s == nil {
		return nil
	}
	data := s.data[:0]
	for _, elem := range s.data {
		if fn(elem) {
			data = append(data, elem)
		}
	}
	s.data = data
	return s
}

// Transform modifies each element of SliceBool according to the specified function.
func (s *SliceBool) Transform(fn func(elem bool) bool) *SliceBool {
	if s == nil {
		return nil
	}
	for i, elem := range s.data {
		s.data[i] = fn(elem)
	}
	return s
}

// Unique modifies SliceBool to keep only the first occurrence of each element (removing any duplicates).
func (s *SliceBool) Unique() *SliceBool {
	if s == nil {
		return nil
	}
	seen := make(map[bool]struct{})
	data := s.data[:0]
	for _, elem := range s.data {
		if _, ok := seen[elem]; !ok {
			data = append(data, elem)
			seen[elem] = struct{}{}
		}
	}
	s.data = data
	return s
}

// Reverse reverses the order of the elements of SliceBool.
func (s *SliceBool) Reverse() *SliceBool {
	if s == nil {
		return nil
	}

	for i := len(s.data)/2 - 1; i >= 0; i-- {
		opp := len(s.data) - 1 - i
		s.Swap(i, opp)
	}

	return s
}

// Shuffle randomly shuffles the order of the elements in SliceBool.
func (s *SliceBool) Shuffle(seed int64) *SliceBool {
	if s == nil {
		return nil
	}

	if seed == 0 {
		seed = time.Now().UnixNano()
	}

	r := rand.New(rand.NewSource(seed))
	r.Shuffle(s.Count(), s.Swap)

	return s
}

// Data returns the raw elements of SliceBool.
func (s *SliceBool) Data() []bool {
	if s == nil {
		return nil
	}
	return s.data
}

// Count returns the number of elements in SliceBool.
func (s *SliceBool) Count() int {
	return len(s.data)
}

// Len returns the number of elements in SliceBool (alias for Count).
func (s *SliceBool) Len() int {
	return s.Count()
}

// Swap swaps the elements in SliceBool specified by the indices i and j.
func (s *SliceBool) Swap(i, j int) {
	s.data[i], s.data[j] = s.data[j], s.data[i]
}

// Clone performs a deep copy of SliceBool and returns it
func (s *SliceBool) Clone() *SliceBool {
	if s == nil {
		return nil
	}
	s2 := new(SliceBool)
	s2.data = make([]bool, len(s.data))
	copy(s2.data, s.data)
	return s2
}

// Equal returns true if the SliceBool is logically equivalent to the specified SliceBool.
func (s *SliceBool) Equal(s2 *SliceBool) bool {
	if s == s2 {
		return true
	}

	if s == nil || s2 == nil {
		return false // has to be false because s == s2 tested earlier
	}

	if len(s.data) != len(s2.data) {
		return false
	}

	for i, elem := range s.data {
		if elem != s2.data[i] {
			return false
		}
	}

	return true
}
