// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at 2020-04-08 01:37:42.861336 +0000 UTC.

package golist

import (
	"fmt"
	"math/rand"
	"sort"
	"time"
)

// SliceInt32 is a slice of type int32.
type SliceInt32 struct {
	data []int32
}

// NewSliceInt32 returns a pointer to a new SliceInt32 initialized with the specified elements.
func NewSliceInt32(elems ...int32) *SliceInt32 {
	s := new(SliceInt32)
	s.data = make([]int32, len(elems))
	for i := 0; i < len(elems); i++ {
		s.data[i] = elems[i]
	}
	return s
}

// Append adds the elements to the end of SliceInt32.
func (s *SliceInt32) Append(elems ...int32) *SliceInt32 {
	if s == nil {
		return nil
	}
	s.data = append(s.data, elems...)
	return s
}

// Prepend adds the elements to the beginning of SliceInt32.
func (s *SliceInt32) Prepend(elems ...int32) *SliceInt32 {
	if s == nil {
		return nil
	}
	s.data = append(elems, s.data...)
	return s
}

// At returns the element in SliceInt32 at the specified index.
func (s *SliceInt32) At(index int) int32 {
	if s.data == nil || len(s.data) == 0 {
		panic("SliceInt32 does not contain any elements")
	}

	if index >= len(s.data) || index < 0 {
		panic(fmt.Sprintf("index %d outside the range of SliceInt32", index))
	}

	return s.data[index]
}

// Set sets the element of SliceInt32 at the specified index.
func (s *SliceInt32) Set(index int, elem int32) *SliceInt32 {
	if s == nil {
		return nil
	}
	s.data[index] = elem
	return s
}

// Insert inserts the elements into SliceInt32 at the specified index.
func (s *SliceInt32) Insert(index int, elems ...int32) *SliceInt32 {
	if s == nil {
		return nil
	}

	// Grow the slice by the number of elements (using the zero value)
	var zero int32
	for i := 0; i < len(elems); i++ {
		s.data = append(s.data, zero)
	}

	// Use copy to move the upper part of the slice out of the way and open a hole.
	copy(s.data[index+len(elems):], s.data[index:])

	// Store the new values
	for i := 0; i < len(elems); i++ {
		s.data[index+i] = elems[i]
	}

	// Return the result.
	return s
}

// Remove removes the element from SliceInt32 at the specified index.
func (s *SliceInt32) Remove(index int) *SliceInt32 {
	if s == nil {
		return nil
	}
	s.data = append(s.data[:index], s.data[index+1:]...)
	return s
}

// Filter removes elements from SliceInt32 that do not satisfy the filter function.
func (s *SliceInt32) Filter(fn func(elem int32) bool) *SliceInt32 {
	if s == nil {
		return nil
	}
	data := s.data[:0]
	for _, elem := range s.data {
		if fn(elem) {
			data = append(data, elem)
		}
	}
	s.data = data
	return s
}

// Transform modifies each element of SliceInt32 according to the specified function.
func (s *SliceInt32) Transform(fn func(elem int32) int32) *SliceInt32 {
	if s == nil {
		return nil
	}
	for i, elem := range s.data {
		s.data[i] = fn(elem)
	}
	return s
}

// Unique modifies SliceInt32 to keep only the first occurrence of each element (removing any duplicates).
func (s *SliceInt32) Unique() *SliceInt32 {
	if s == nil {
		return nil
	}
	seen := make(map[int32]struct{})
	data := s.data[:0]
	for _, elem := range s.data {
		if _, ok := seen[elem]; !ok {
			data = append(data, elem)
			seen[elem] = struct{}{}
		}
	}
	s.data = data
	return s
}

// Reverse reverses the order of the elements of SliceInt32.
func (s *SliceInt32) Reverse() *SliceInt32 {
	if s == nil {
		return nil
	}

	for i := len(s.data)/2 - 1; i >= 0; i-- {
		opp := len(s.data) - 1 - i
		s.Swap(i, opp)
	}

	return s
}

// Shuffle randomly shuffles the order of the elements in SliceInt32.
func (s *SliceInt32) Shuffle(seed int64) *SliceInt32 {
	if s == nil {
		return nil
	}

	if seed == 0 {
		seed = time.Now().UnixNano()
	}

	r := rand.New(rand.NewSource(seed))
	r.Shuffle(s.Count(), s.Swap)

	return s
}

// Data returns the raw elements of SliceInt32.
func (s *SliceInt32) Data() []int32 {
	if s == nil {
		return nil
	}
	return s.data
}

// Count returns the number of elements in SliceInt32.
func (s *SliceInt32) Count() int {
	return len(s.data)
}

// Len returns the number of elements in SliceInt32 (alias for Count).
func (s *SliceInt32) Len() int {
	return s.Count()
}

// Swap swaps the elements in SliceInt32 specified by the indices i and j.
func (s *SliceInt32) Swap(i, j int) {
	s.data[i], s.data[j] = s.data[j], s.data[i]
}

// Less returns true if the SliceInt32 element at index i is less than the element at index j.
func (s *SliceInt32) Less(i, j int) bool {
	return s.data[i] < s.data[j]
}

// Sort sorts the elements of SliceInt32 in increasing order.
func (s *SliceInt32) Sort() *SliceInt32 {
	if s == nil {
		return nil
	}
	sort.Sort(s)
	return s
}

// Min returns the smallest (least ordered) element in SliceInt32.
func (s *SliceInt32) Min() int32 {
	if s.data == nil || len(s.data) == 0 {
		panic("SliceInt32 does not contain any elements")
	}
	// start with the first value
	min := s.data[0]
	for _, elem := range s.data[1:] {
		if elem < min {
			min = elem
		}
	}
	return min
}

// Max returns the largest (greatest ordered) element in SliceInt32.
func (s *SliceInt32) Max() int32 {
	if s.data == nil || len(s.data) == 0 {
		panic("SliceInt32 does not contain any elements")
	}
	// start with the first value
	max := s.data[0]
	for _, elem := range s.data[1:] {
		if elem > max {
			max = elem
		}
	}
	return max
}

// Clone performs a deep copy of SliceInt32 and returns it
func (s *SliceInt32) Clone() *SliceInt32 {
	if s == nil {
		return nil
	}
	s2 := new(SliceInt32)
	s2.data = make([]int32, len(s.data))
	copy(s2.data, s.data)
	return s2
}

// Equal returns true if the SliceInt32 is logically equivalent to the specified SliceInt32.
func (s *SliceInt32) Equal(s2 *SliceInt32) bool {
	if s == s2 {
		return true
	}

	if s == nil || s2 == nil {
		return false // has to be false because s == s2 tested earlier
	}

	if len(s.data) != len(s2.data) {
		return false
	}

	for i, elem := range s.data {
		if elem != s2.data[i] {
			return false
		}
	}

	return true
}
